"""make band_id optional in AlbumBase

Revision ID: acaf08c0e5ab
Revises: b2c990dfe48e
Create Date: 2025-04-29 03:02:03.103326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'acaf08c0e5ab'
down_revision: Union[str, None] = 'b2c990dfe48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
